mercari/urls.py
from django.urls import path
from . import views

app_name='mercari'

urlpatterns = [
    path('exclude_seller', views.exclude_seller, name='exclude_seller'),
    path('delete_exclude_seller', views.delete_exclude_seller, name='delete_exclude_seller'),
    path('amazon_offer_research', views.amazon_offer_research, name='amazon_offer_research'),
    path('research', views.research, name='research'),
    path('research_amazon_by_mercari', views.research_amazon_by_mercari, name='research_amazon_by_mercari'),
    path('feed_amazon_new', views.feed_amazon_new, name='feed_amazon_new'),
    path('feed_amazon_offer', views.feed_amazon_offer, name='feed_amazon_offer'),
    path('export_amazon_new_csv', views.export_amazon_new_csv, name='export_amazon_new_csv'),
    path('export_amazon_new_csv_from_candidate', views.export_amazon_new_csv_from_candidate, name='export_amazon_new_csv_from_candidate'),
    path('export_amazon_offer_csv', views.export_amazon_offer_csv, name='export_amazon_offer_csv'),
    path('download_amazon_csv', views.download_amazon_csv, name='download_amazon_csv'),
    path('edit_amazon_offer', views.edit_amazon_offer, name='edit_amazon_offer'),
    path('edit_amazon_new', views.edit_amazon_new, name='edit_amazon_new'),
    path('edit_amazon_new_candidate', views.edit_amazon_new_candidate, name='edit_amazon_new_candidate'),
    path('item_list', views.item_list, name='item_list'),
    path('import_item', views.import_item, name='import_item'),

    path('api/progress/import_report', views.import_report_progress, 
        name='api.progress.import_report'),
    path('api/progress/amazon_offer_research', views.amazon_offer_research_progress, 
        name='api.progress.amazon_offer_research'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

top/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

yahoo/urls.py
from django.urls import path
from . import views

app_name='yahoo'

urlpatterns = [
    path('test', views.test, name='test'),
    path('exclude_seller', views.exclude_seller, name='exclude_seller'),
    path('delete_exclude_seller', views.delete_exclude_seller, name='delete_exclude_seller'),
    path('amazon_offer_research', views.amazon_offer_research, name='amazon_offer_research'),
    path('research', views.research, name='research'),
    path('research_amazon_by_yahoo', views.research_amazon_by_yahoo, name='research_amazon_by_yahoo'),
    path('feed_amazon_new', views.feed_amazon_new, name='feed_amazon_new'),
    path('feed_amazon_offer', views.feed_amazon_offer, name='feed_amazon_offer'),
    path('export_amazon_new_csv', views.export_amazon_new_csv, name='export_amazon_new_csv'),
    path('export_amazon_offer_csv', views.export_amazon_offer_csv, name='export_amazon_offer_csv'),
    path('export_amazon_new_csv_from_candidate', views.export_amazon_new_csv_from_candidate, name='export_amazon_new_csv_from_candidate'),
    path('download_amazon_csv', views.download_amazon_csv, name='download_amazon_csv'),
    path('edit_amazon_offer', views.edit_amazon_offer, name='edit_amazon_offer'),
    path('edit_amazon_new', views.edit_amazon_new, name='edit_amazon_new'),
    path('edit_amazon_new_candidate', views.edit_amazon_new_candidate, name='edit_amazon_new_candidate'),
    path('item_list', views.item_list, name='item_list'),
    path('import_report', views.import_report, name='import_report'),
    path('download_item_list', views.download_item_list, name='download_item_list'),
    path('import_csv', views.import_csv, name='import_csv'),

    path('api/progress/import_report', views.import_report_progress, 
        name='api.progress.import_report'),
    path('api/progress/amazon_offer_research', views.amazon_offer_research_progress, 
        name='api.progress.amazon_offer_research'),
    


]

yahoo/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.dispatch import receiver
from django.conf import settings
from richs_utils import RichsUtils


import os


class YahooExcludeSeller(models.Model):
    class Meta:
        db_table = 'yahoo_exclude_seller'
        verbose_name = '禁止セラー個別設定'
        verbose_name_plural = '禁止セラー個別設定'

    seller_id = models.CharField(verbose_name="セラーID", max_length=128,db_index=True)
    memo = models.CharField(verbose_name="メモ", max_length=128, null=True, blank=True)
    author = models.ForeignKey('accounts.User', verbose_name="ユーザ名", on_delete=models.CASCADE,db_index=True) 
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return '[{}] {}'.format(self.author.username, self.seller_id)

# 禁止セラーのマスター
class YahooExcludeSellerMaster(models.Model):
    class Meta:
        db_table = 'yahoo_exclude_seller_master'
        verbose_name = '新規ユーザー禁止セラーマスタ'
        verbose_name_plural = '新規ユーザー禁止セラーマスタ'



    seller_id = models.CharField(verbose_name="セラーID", max_length=128,db_index=True)

    
    def __str__(self):
        return self.seller_id

# プルダウンの選択肢
CONDITION_CHOICES = (
    ('New', '新品'),
    ('Refurbished', '再生品'),
    ('UsedLikeNew', '中古-ほぼ新品'),
    ('UsedVeryGood', '中古-非常に良い'),
    ('UsedGood', '中古-良い'),
    ('UsedAcceptable', '中古-可'),
    ('CollectibleLikeNew', 'コレクター商品-ほぼ新品'),
    ('CollectibleVeryGood', 'コレクター商品-非常に良い'),    
    ('CollectibleGood', 'コレクター商品-良い'),
    ('CollectibleAcceptable', 'コレクター商品-可'),
)

# 商品コードのタイプ
EXTERNAL_PRODUCT_ID_TYPE_CHOICES = (
    ('EAN','EAN'),
    ('ISBN','ISBN'),
    ('UPC','UPC'),
    ('ASIN','ASIN'),
    ('GTIN','GTIN'),
)

# 出品商品
class YahooToAmazonItem(models.Model):
    class Meta:
        db_table = 'yahoo_to_amazon_item'

    local_id = None
    status_message = None
    inventory_message= None
    feed_type= models.IntegerField(verbose_name="出品種別",null=True) # 0:新規, 1:相乗り, 3:取り込み, 4:取り込み更新中
    item_sku= models.CharField(verbose_name="出品者SKU",max_length=64,null=True, db_index=True)
    item_name= models.CharField(verbose_name="商品名",max_length=256,null=True, db_index=True) 
    external_product_id= models.CharField(verbose_name="商品コード(JANコード等)",max_length=64,null=True, blank=True)
    external_product_id_type= models.CharField(verbose_name="商品コードのタイプ",max_length=16,null=True, blank=True,choices=EXTERNAL_PRODUCT_ID_TYPE_CHOICES)
    brand_name= models.CharField(verbose_name="ブランド名",max_length=256,null=True, blank=True)
    manufacturer= models.CharField(verbose_name="メーカー名",max_length=256,null=True, blank=True)
    feed_product_type= models.CharField(verbose_name="商品タイプ",max_length=64,null=True, blank=True)
    part_number= models.CharField(verbose_name="メーカー型番",max_length=256,null=True, blank=True)
    product_description= models.TextField(verbose_name="商品説明文",null=True, blank=True)
    bullet_point = models.TextField(verbose_name="商品の仕様",null=True, blank=True)
    model= models.CharField(verbose_name="型番",max_length=256,null=True, blank=True)
    quantity = models.IntegerField(verbose_name="在庫数(登録時)",null=True, blank=True)
    fulfillment_latency= models.IntegerField(verbose_name="リードタイム(登録時)",null=True, blank=True,db_index=True) 
    condition_type= models.CharField(verbose_name="商品のコンディション",max_length=32,choices=CONDITION_CHOICES,null=True, blank=True)
    standard_price= models.IntegerField(verbose_name="商品の販売価格",null=True)
    standard_price_points= models.IntegerField(verbose_name="ポイント",null=True, blank=True, validators=[MaxValueValidator(50)])
    condition_note= models.TextField(verbose_name="商品のコンディション説明",null=True)
    item_weight= models.IntegerField(verbose_name="商品の重量",null=True, blank=True)
    item_weight_unit_of_measure= models.CharField(verbose_name="商品の重量の単位",max_length=16,null=True, blank=True)
    item_height= models.IntegerField(verbose_name="商品の高さ",null=True, blank=True)
    item_length= models.IntegerField(verbose_name="商品の長さ",null=True, blank=True)
    item_width= models.IntegerField(verbose_name="商品の幅",null=True, blank=True)
    item_length_unit_of_measure= models.CharField(verbose_name="商品寸法の単位",max_length=16,null=True, blank=True)
    recommended_browse_nodes= models.CharField(verbose_name="推奨ブラウズノード",max_length=64,null=True, blank=True)
    generic_keywords= models.CharField(verbose_name="検索キーワード",max_length=256,null=True, blank=True)
    main_image_url= models.CharField(verbose_name="商品メイン画像URL",max_length=256,null=True)
    other_image_url1= models.CharField(verbose_name="商品サブ画像URL1",max_length=256,null=True, blank=True)
    other_image_url2= models.CharField(verbose_name="商品サブ画像URL2",max_length=256,null=True, blank=True)
    other_image_url3= models.CharField(verbose_name="商品サブ画像URL3",max_length=256,null=True, blank=True)    
    csv_flag= models.IntegerField(verbose_name="CSV出力状態",null=True,db_index=True) 
    format= models.CharField(verbose_name="フォーマット",max_length=32,null=True, blank=True,db_index=True) 
    category= models.CharField(verbose_name="カテゴリー",max_length=32,null=True, blank=True)
    purchaseo_seller_id= models.CharField(verbose_name="セーラーID(初回仕入れ時)",max_length=64,null=True, blank=True)
    purchase_item_id= models.CharField(verbose_name="商品ID(登録時)",max_length=64,null=True, blank=True)
    purchase_quantity= models.IntegerField(verbose_name="仕入数(初回仕入れ時)",null=True, blank=True)
    purchase_fulfillment_latency= models.IntegerField(verbose_name="リードタイム(初回仕入れ時)",null=True, blank=True,db_index=True) 
    purchase_price= models.IntegerField(verbose_name="仕入れ価格(初回仕入れ時)",null=True, blank=True)
    purchase_similarity= models.FloatField(verbose_name="類似度(初回仕入れ時)",null=True, blank=True)
    current_purchase_seller_id= models.CharField(verbose_name="セーラーID(現在)",max_length=32,null=True, blank=True,db_index=True)
    current_purchase_item_id= models.CharField(verbose_name="商品ID(現在)",max_length=32,null=True, blank=True,db_index=True) 
    current_purchase_quantity= models.IntegerField(verbose_name="仕入数(現在)",null=True, blank=True)
    current_purchase_fulfillment_latency= models.IntegerField(verbose_name="リードタイム(現在)",null=True, blank=True,db_index=True) 
    current_purchase_price= models.IntegerField(verbose_name="仕入れ価格(現在)",null=True, blank=True)
    current_similarity= models.FloatField(verbose_name="類似度(現在)",null=True, blank=True)
    amazon_price= models.IntegerField(verbose_name="アマゾン最安値",null=True, blank=True)

    update_fulfillment_latency_request = models.BooleanField(verbose_name="リードタイム更新要求",null=True, blank=True, db_index=True)
    research_request = models.BooleanField(verbose_name="在庫検索要求", null=True, blank=True, db_index=True)
    update_quantity_request = models.BooleanField(verbose_name="在庫更新要求", null=True, blank=True, db_index=True)

    # 0:確定レコード
    # 1X: インポート中, 10:CSVロード直後, 12:メルカリで商品収集完了, 13:アマゾンで商品情報収集完了,     
    # 2X:               20:取り下げ   21:復活中


    record_type = models.IntegerField(verbose_name="レコードタイプ",null=True, blank=True, db_index=True)
    
    author = models.ForeignKey('accounts.User', verbose_name="ユーザ名", on_delete=models.CASCADE,db_index=True) 
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.item_sku

# ファイルを削除する。
@receiver(models.signals.post_delete, sender=YahooToAmazonItem)
def delete_file(sender, instance, **kwargs):    
    base_dir = os.path.join(settings.RICHS_FOLDER_IMAGE, 'yahoo', instance.author.username)
    try:
        RichsUtils.delete_file(base_dir, instance.main_image_url)
        RichsUtils.delete_file(base_dir, instance.other_image_url1)
        RichsUtils.delete_file(base_dir, instance.other_image_url2)
        RichsUtils.delete_file(base_dir, instance.other_image_url3)
    except:
        pass


# 出品商品
class YahooToAmazonItemCandidate(models.Model):
    class Meta:
        db_table = 'yahoo_to_amazon_item_candidate'

    local_id = None
    status_message = None
    inventory_message= None
    feed_type= models.IntegerField(verbose_name="出品種別",null=True) # 0:新規, 1:相乗り, 3:取り込み
    item_sku= models.CharField(verbose_name="出品者SKU",max_length=64,null=True, db_index=True)
    item_name= models.CharField(verbose_name="商品名",max_length=256,null=True, db_index=True) 
    external_product_id= models.CharField(verbose_name="商品コード(JANコード等)",max_length=64,null=True, blank=True)
    external_product_id_type= models.CharField(verbose_name="商品コードのタイプ",max_length=16,null=True, blank=True,choices=EXTERNAL_PRODUCT_ID_TYPE_CHOICES)
    brand_name= models.CharField(verbose_name="ブランド名",max_length=256,null=True, blank=True)
    manufacturer= models.CharField(verbose_name="メーカー名",max_length=256,null=True, blank=True)
    feed_product_type= models.CharField(verbose_name="商品タイプ",max_length=64,null=True, blank=True)
    part_number= models.CharField(verbose_name="メーカー型番",max_length=256,null=True, blank=True)
    product_description= models.TextField(verbose_name="商品説明文",null=True, blank=True)
    bullet_point = models.TextField(verbose_name="商品の仕様",null=True, blank=True)
    model= models.CharField(verbose_name="型番",max_length=256,null=True, blank=True)
    quantity = models.IntegerField(verbose_name="在庫数(登録時)",null=True, blank=True)
    fulfillment_latency= models.IntegerField(verbose_name="リードタイム(登録時)",null=True, blank=True,db_index=True) 
    condition_type= models.CharField(verbose_name="商品のコンディション",max_length=32,choices=CONDITION_CHOICES,null=True, blank=True)
    standard_price= models.IntegerField(verbose_name="商品の販売価格",null=True)
    standard_price_points= models.IntegerField(verbose_name="ポイント",null=True, blank=True, validators=[MaxValueValidator(50)])
    condition_note= models.TextField(verbose_name="商品のコンディション説明",null=True)
    item_weight= models.IntegerField(verbose_name="商品の重量",null=True, blank=True)

yahoo/templates/yahoo/edit_amazon_new.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}メルカリッチくん{% endblock %}


{% block script_onload %}

Utils.selectYahoo();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

$(function () {
　$("#main_image_file").change(function () {
　　$("#id_main_image_url").val($(this).val());
　});

　$("#other_image_file1").change(function () {
　　$("#id_other_image_url1").val($(this).val());
　});

　$("#other_image_file2").change(function () {
　　$("#id_other_image_url2").val($(this).val());
　});

　$("#other_image_file3").change(function () {
　　$("#id_other_image_url3").val($(this).val());
　});

  $("#id_category").change(function () {
    setSelect('#id_recommended_browse_nodes', '/api/amazon_child_category_user/?format=json&category=' + $(this).val());
  });

　$("#id_manufacturer").change(function () {
    $("#id_brand_name").val($(this).val());
　});
　$("#id_brand_name").val($("#id_manufacturer").val());

});

  function setSelect(dom_id, url) {
    var dropdown = $(dom_id);
    dropdown.empty();
    $.getJSON(url, function (data) {
        $.each(data, function (key, entry) {
            dropdown.append($('<option></option>').attr('value', entry.value).attr('id', entry.value).text(entry.name));
	})
    });
  }



{% endblock %}

{% block html_body %} 

<center><h2>新規出品編集</h2></center>
<br>
<form  action="{% url 'yahoo:edit_amazon_new' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <center>
    <table width="90%" border=1 style="table-layout: fixed;">
      <tr>
	<td width="15%">SKU</td>
	<td colspan="7" width="85%">{{ form.item_sku | add_class:"feed-form-input" | attr:"readonly:readonly" }}</td>
      </tr>
      <tr>
	<td width="15%">コード</td>
	<td colspan="3" width="25%">{{ form.external_product_id_type | add_class:"feed-form-input" }}</td>
	<td colspan="4" width="60%">{{ form.external_product_id | add_class:"feed-form-input" }}</td>
      </tr>    
      <tr>
	<td width="15%">商品名</td>
	<td colspan="7" width="85%">{{ form.item_name | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">メーカ名</td>
	<td colspan="7" width="85%">{{ form.manufacturer | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">ブランド名</td>
	<td colspan="7" width="85%">{{ form.brand_name | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">メーカ型番</td>
	<td colspan="7" width="85%">{{ form.part_number | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">コンデション</td>
	<td colspan="7" width="85%">{{ form.condition_type | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">コンデションの説明</td>
	<td colspan="7" width="85%">{{ form.condition_note | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">商品の説明</td>
	<td colspan="7" width="85%">{{ form.product_description | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">商品の仕様</td>
	<td colspan="7" width="85%">{{ form.bullet_point | add_class:"feed-form-input" }}</td>
      </tr>              
      <tr>
	<td width="15%">検索キーワード１</td>
	<td colspan="7" width="85%">{{ form.generic_keywords | add_class:"feed-form-input" }}</td>
      </tr>    
      <tr>
	<td width="15%">カテゴリ（大分類）</td>
	<td colspan="7" width="85%">{{ form.category | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">カテゴリ（詳細）</td>
	<td colspan="7" width="85%">{{ form.recommended_browse_nodes | add_class:"feed-form-input" }}</td>
      </tr>
      <!--
      <tr>
	<td width="15%">長さ</td>
	<td colspan="7" width="85%">{{ form.item_length }}</td>
      </tr>
      <tr>
	<td width="15%">幅</td>
	<td colspan="7" width="85%">{{ form.item_width }}</td>
      </tr>
      <tr>
	<td width="15%">高さ</td>
	<td colspan="7" width="85%">{{ form.item_height }}</td>
      </tr>
      <tr>
	<td width="15%">サイズ単位</td>
	<td colspan="7" width="85%">{{ form.item_length_unit_of_measure }}</td>
      </tr>    
      <tr>
	<td width="15%">重さ</td>
	<td colspan="7" width="85%">{{ form.item_weight }}</td>
      </tr>
      <tr>
	<td width="15%">重さ単位</td>
	<td colspan="7" width="85%">{{ form.item_weight_unit_of_measure }}</td>
      </tr>
      -->

      {% if images %}
      <tr>
	<td width="15%">
	  {% if images.0 %}
	  <img src="{{ base_url }}/{{ images.0 }}" id="img0" width="100%" />
	  <center>{{ images.0 }}</center>
	  {% endif %}
	</td>
	<td width="10%">
	  {% if images.0 %}
	  <center>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img0', '#id_main_image_url');">メイン</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img0', '#id_other_image_url1');">その他1</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img0', '#id_other_image_url2');">その他2</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img0', '#id_other_image_url3');">その他3</button>
	  </center>
	  {% endif %}
	</td>
	
	<td width="15%">
	  {% if images.1 %}
	  <img src="{{ base_url }}/{{ images.1 }}" id="img1" width="100%" />
	  <center>{{ images.1 }}</center>
	  {% endif %}
	</td>
	<td width="10%">
	  {% if images.1 %}
	  <center>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img1', '#id_main_image_url');">メイン</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img1', '#id_other_image_url1');">その他1</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img1', '#id_other_image_url2');">その他2</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img1', '#id_other_image_url3');">その他3</button>
	  </center>
	  {% endif %}
	</td>

	<td width="15%">
	  {% if images.2 %}
	  <img src="{{ base_url }}/{{ images.2 }}" id="img2" width="100%" />
	  <center>{{ images.2 }}</center>
	  {% endif %}
	</td>
	<td width="10%">
	  {% if images.2 %}
	  <center>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img2', '#id_main_image_url');">メイン</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img2', '#id_other_image_url1');">その他1</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img2', '#id_other_image_url2');">その他2</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img2', '#id_other_image_url3');">その他3</button>
	  </center>
	  {% endif %}
	</td>

	<td width="15%">
	  {% if images.3 %}
	  <img src="{{ base_url }}/{{ images.3 }}" id="img3" width="100%" />
	  <center>{{ images.3 }}</center>
	  {% endif %}
	</td>
	<td width="10%">
	  {% if images.3 %}
	  <center>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img3', '#id_main_image_url');">メイン</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img3', '#id_other_image_url1');">その他1</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img3', '#id_other_image_url2');">その他2</button><br>
	    <button type="button" class="feed-form-img-select-button" onClick="copy_image_path('#img3', '#id_other_image_url3');">その他3</button>
	  </center>
	  {% endif %}
	</td>
      </tr>
      {% endif %}

      <tr>
	<td width="15%">商品画像(メイン)</td>
	<td colspan="6" width="75%">{{ form.main_image_url | add_class:"feed-form-input"}}</td>
	<td width="10%">
	  <label for="main_image_file" class="feed-form-file-select-label">
	    ＋写真を選択<input type="file" id="main_image_file" name="main_image_file" style="display:none;" accept="image/jpeg">
	  </label>
	</td>
      </tr>
      <tr>
	<td width="15%">商品画像(その他1)</td>
	<td colspan="6" width="75%">{{ form.other_image_url1 | add_class:"feed-form-input" }}</td>
	<td width="10%">
	  <label for="other_image_file1" class="feed-form-file-select-label">
	    ＋写真を選択<input type="file" id="other_image_file1" name="other_image_file1"  style="display:none;" accept="image/jpeg">
	  </label>
	</td>	
      </tr>
      <tr>
	<td width="15%">商品画像(その他2)</td>
	<td colspan="6" width="75%">{{ form.other_image_url2 | add_class:"feed-form-input" }}</td>
	<td width="10%" valign="middle">
	  <label for="other_image_file2" class="feed-form-file-select-label">
	    ＋写真を選択<input type="file" id="other_image_file2" name="other_image_file2" style="display:none;" accept="image/jpeg">
	  </label>
	</td>	
      </tr>
      <tr>
	<td width="15%">商品画像(その他3)</td>
	<td colspan="6" width="75%">{{ form.other_image_url3 | add_class:"feed-form-input" }}</td>
	<td width="10%">
	  <label for="other_image_file3" class="feed-form-file-select-label">
	    ＋写真を選択<input type="file" id="other_image_file3" name="other_image_file3" style="display:none;" accept="image/jpeg">
	  </label>
	</td>	
      </tr>
      <tr>
	<td width="15%">販売価格</td>
	<td colspan="7" width="85%">{{ form.standard_price | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">ポイント</td>
	<td colspan="7" width="85%">{{ form.standard_price_points | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">在庫数</td>
	<td colspan="7" width="85%">{{ form.quantity  | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td width="15%">リードタイム（日）</td>
	<td colspan="7" width="85%">{{ form.fulfillment_latency  | add_class:"feed-form-input" }}</td>
      </tr>
      <tr>
	<td colspan="8" width="100%">
	  <input type="submit" value="登録">
	</td>
      </tr>
    </table>
  </center>

</form>

<script>

  function copy_image_path(from, to) {
     $(to).val($(from).attr('src').split('/').pop());
  }
  
</script>

<br>
<br>
<br>

{% endblock %}

yahoo/templates/yahoo/exclude_seller.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}メルカリッチくん{% endblock %}


{% block script_onload %}

Utils.selectYahoo();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

{% endblock %}

{% block html_body %} 
<div class="container">
  <center><h2>検索除外セラーID</h2></center>

  <form class="form-horizontal" action="{% url 'yahoo:exclude_seller'  %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.seller_id.label_tag }}<br>
      {{ form.seller_id | add_class:"form-control" }}<br>
      {{ form.memo.label_tag }}<br>
      {{ form.memo | add_class:"form-control" }}<br>
    </div>
    <input type="submit" value="登録" />
  </form>

  <br>

  {% if sellers.count > 0 %} 
  <form class="form-horizontal" action="{% url 'yahoo:delete_exclude_seller'  %}" method="post">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="col-xs-1">削除</th>
          <th>セラーID</th>
	  <th>メモ</th>
        </tr>
      </thead>
      <tbody>
        {% for seller in sellers %}
        <tr>
          <td><input type="checkbox" name="delete_ids" value="{{ seller.id }}"></td>
          <td>{{ seller.seller_id }}</td>
	  <td>{% if seller.memo != None %}{{ seller.memo }}{% endif %}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% csrf_token %}
    <input type="submit" value="削除">
  </form>
</div>

{% endif %}
{% endblock %}