mercari/urls.py
from django.urls import path
from . import views

app_name='mercari'

urlpatterns = [
    path('exclude_seller', views.exclude_seller, name='exclude_seller'),
    path('delete_exclude_seller', views.delete_exclude_seller, name='delete_exclude_seller'),
    path('amazon_offer_research', views.amazon_offer_research, name='amazon_offer_research'),
    path('research', views.research, name='research'),
    path('research_amazon_by_mercari', views.research_amazon_by_mercari, name='research_amazon_by_mercari'),
    path('feed_amazon_new', views.feed_amazon_new, name='feed_amazon_new'),
    path('feed_amazon_offer', views.feed_amazon_offer, name='feed_amazon_offer'),
    path('export_amazon_new_csv', views.export_amazon_new_csv, name='export_amazon_new_csv'),
    path('export_amazon_new_csv_from_candidate', views.export_amazon_new_csv_from_candidate, name='export_amazon_new_csv_from_candidate'),
    path('export_amazon_offer_csv', views.export_amazon_offer_csv, name='export_amazon_offer_csv'),
    path('download_amazon_csv', views.download_amazon_csv, name='download_amazon_csv'),
    path('edit_amazon_offer', views.edit_amazon_offer, name='edit_amazon_offer'),
    path('edit_amazon_new', views.edit_amazon_new, name='edit_amazon_new'),
    path('edit_amazon_new_candidate', views.edit_amazon_new_candidate, name='edit_amazon_new_candidate'),
    path('item_list', views.item_list, name='item_list'),
    path('import_item', views.import_item, name='import_item'),

    path('api/progress/import_report', views.import_report_progress, 
        name='api.progress.import_report'),
    path('api/progress/amazon_offer_research', views.amazon_offer_research_progress, 
        name='api.progress.amazon_offer_research'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

settings_amazon/urls.py
from django.urls import path
from rest_framework import routers
from . import views
#from .views import UserViewSet, EntryViewSet

from django.conf.urls import url, include

app_name = 'settings_amazon'

urlpatterns = [
    path('api_settings/', views.api_settings, name='api_settings'),
    path('default/', views.default_settings, name='default'),
    path('exclude_asin', views.exclude_asin, name='exclude_asin'),
    path('delete_exclude_asin', views.delete_exclude_asin, name='delete_exclude_asin'),
    path('brand/', views.brand_settings, name='brand'),
    path('delete_brands/', views.delete_brands, name='delete_brands'),
    path('category/', views.category, name='category'),
    path('category_parent', views.category_parent, name='category_parent'),
    path('category_child', views.category_child, name='category_child'),
    path('feed_price_settings', views.feed_price_settings, name='feed_price_settings'),
    path('api/token_validation', views.token_validation, name='api_token_validation'),
]

router = routers.DefaultRouter()
router.register(r'amazon_category', views.AmazonParentCategorySerializerViewSet)
router.register(r'amazon_brand', views.AmazonBrandSerializerViewSet)
router.register(r'amazon_category_user', views.AmazonParentCategoryUserSerializerViewSet)
router.register(r'amazon_child_category', views.AmazonChildCategorySerializerViewSet)
router.register(r'amazon_child_category_user', views.AmazonChildCategoryUserSerializerViewSet)

top/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

yahoo/urls.py
from django.urls import path
from . import views

app_name='yahoo'

urlpatterns = [
    path('test', views.test, name='test'),
    path('exclude_seller', views.exclude_seller, name='exclude_seller'),
    path('delete_exclude_seller', views.delete_exclude_seller, name='delete_exclude_seller'),
    path('amazon_offer_research', views.amazon_offer_research, name='amazon_offer_research'),
    path('research', views.research, name='research'),
    path('research_amazon_by_yahoo', views.research_amazon_by_yahoo, name='research_amazon_by_yahoo'),
    path('feed_amazon_new', views.feed_amazon_new, name='feed_amazon_new'),
    path('feed_amazon_offer', views.feed_amazon_offer, name='feed_amazon_offer'),
    path('export_amazon_new_csv', views.export_amazon_new_csv, name='export_amazon_new_csv'),
    path('export_amazon_offer_csv', views.export_amazon_offer_csv, name='export_amazon_offer_csv'),
    path('export_amazon_new_csv_from_candidate', views.export_amazon_new_csv_from_candidate, name='export_amazon_new_csv_from_candidate'),
    path('download_amazon_csv', views.download_amazon_csv, name='download_amazon_csv'),
    path('edit_amazon_offer', views.edit_amazon_offer, name='edit_amazon_offer'),
    path('edit_amazon_new', views.edit_amazon_new, name='edit_amazon_new'),
    path('edit_amazon_new_candidate', views.edit_amazon_new_candidate, name='edit_amazon_new_candidate'),
    path('item_list', views.item_list, name='item_list'),
    path('import_report', views.import_report, name='import_report'),
    path('download_item_list', views.download_item_list, name='download_item_list'),
    path('import_csv', views.import_csv, name='import_csv'),

    path('api/progress/import_report', views.import_report_progress, 
        name='api.progress.import_report'),
    path('api/progress/amazon_offer_research', views.amazon_offer_research_progress, 
        name='api.progress.amazon_offer_research'),
    


]

templates/auth_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ja" >
<head>
  <title>ログイン</title>
  <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
  <link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
  <meta name="robots" content="NONE,NOARCHIVE">
  <link rel="shortcut icon" href="/static/favicon.ico?v=1">
</head>

<body class=" login"
  data-admin-utc-offset="32400">
  <!-- Container -->
  <div id="container">
    <!-- Header -->
    <div id="header">
      <div id="branding">
	<h1 id="site-name"><a href="#">メルカリッチくん</a></h1>
        </div>       
    </div>
    <!-- END Header -->
    <!-- Content -->
    <div id="content" class="colM">
      <div id="content-main">
	{% block content %}{% endblock %}
      </div>  
      <br class="clear">
    </div>
    <!-- END Content -->
    <div id="footer"></div>
  </div>
  <!-- END Container -->
</div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="NONE,NOARCHIVE">
    <title>{% block title %}My amazing site{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70.0-2014.11.23/jquery.blockUI.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script type="text/javascript" src="{% static 'js/Utils.js' %}?v=1"></script>
    <link rel="stylesheet" href="{% static 'css/richs.css' %}">
    <link rel="shortcut icon" href="/static/favicon.ico?v=1">


    <style>
      .dropdown:hover > .dropdown-menu{
      display: block;
      }
      body {
      padding-top: 70px; 
      }
    </style>
  </head>


  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
	    <span class="sr-only">Toggle navigation</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="/home">HOME</a>
	</div>
	<div class="collapse navbar-collapse" id="navbarEexample">
	  <ul class="nav navbar-nav">
	    <li class="dropdown1 dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">ヤフオクリサーチ<span class="caret"></span></a>
	      <ul class="dropdown-menu" role="menu">
		<li><a href="{% url 'yahoo:research' %}">商品リサーチ</a></li>
		<li><a href="{% url 'yahoo:amazon_offer_research' %}">Amazon一括出品データ作成（ヤフオク）</a></li>	    
		<li><a href="{% url 'yahoo:exclude_seller' %}">除外セラーID</a></li>
		<li><a href="{% url 'yahoo:item_list' %}">出品商品一覧</a></li>
		<li><a href="{% url 'yahoo:import_report' %}">AMAZON出品レポート取込</a></li>
		<li><a href="{% url 'yahoo:export_amazon_offer_csv' %}">AMAZON相乗り出品用CSV出力</a></li>
		<li><a href="{% url 'yahoo:export_amazon_new_csv' %}">AMAZON新規出品用CSV出力</a></li>
		<li><a href="{% url 'yahoo:export_amazon_new_csv_from_candidate' %}">AMAZON新規出品用CSV出力（自動生成）</a></li>
		<li><a href="{% url 'yahoo:download_amazon_csv' %}">AMAZON相乗り・新規出品用ファイルダウンロード</a></li>
	      </ul>
	    </li>
	    <li class="dropdown2 dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">メルカリリサーチ<span class="caret"></span></a>
	      <ul class="dropdown-menu" role="menu">
		<li><a href="{% url 'mercari:research' %}">商品リサーチ</a></li>
		<li><a href="{% url 'mercari:amazon_offer_research' %}">Amazon一括出品データ生成（メルカリ）</a></li>	    
		<li><a href="{% url 'mercari:exclude_seller' %}">除外セラーID</a></li>
		<li><a href="{% url 'mercari:item_list' %}">出品商品一覧</a></li>
		<li><a href="{% url 'mercari:import_item' %}">AMAZON商品取込</a></li>
		<li><a href="{% url 'mercari:export_amazon_offer_csv' %}">AMAZON相乗り出品用CSV出力</a></li>
		<li><a href="{% url 'mercari:export_amazon_new_csv' %}">AMAZON新規出品用CSV出力</a></li>
		<li><a href="{% url 'mercari:export_amazon_new_csv_from_candidate' %}">AMAZON新規出品用CSV出力 (自動生成)</a></li>
		<li><a href="{% url 'mercari:download_amazon_csv' %}">AMAZON相乗り・新規出品用ファイルダウンロード</a></li>
	      </ul>
	    </li>
	    <li class="dropdown3 dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">AMAZON設定<span class="caret"></span></a>
	      <ul class="dropdown-menu" role="menu">
		<li><a href="{% url 'settings_amazon:api_settings' %}">AmazonAPI設定</a></li>
		<li><a href="{% url 'settings_amazon:feed_price_settings' %}">Amazon利益設定</a></li>
		<li><a href="{% url 'settings_amazon:default' %}">Amazonデフォルト設定</a></li>
		<li><a href="{% url 'settings_amazon:category' %}">Amazonカテゴリー順序設定</a></li>
		<li><a href="{% url 'settings_amazon:brand' %}">Amazonブランド設定</a></li>
		<li><a href="{% url 'settings_amazon:exclude_asin' %}">Amazon禁止ASIN設定</a></li>
	      </ul>
	    </li>
	  </ul>
	  <div class="nav navbar-right">
	    <a href="/accounts/logout">
	      <button type="button" class="btn btn-default navbar-btn navbar-right" style="margin-right: 10px;">
		ログアウト
	      </button>
	    </a>
	    <a href="/accounts/password_change">
	      <button type="button" class="btn btn-default navbar-btn navbar-right" style="margin-right: 10px;">
		パスワード変更
	      </button>
	    </a>
	  </div>
	</div>
      </div>
    </nav>


    <script>
      {% block script_top %}{% endblock %}
      window.onload = function() {

      // ローディング画面
      $("form").submit(function() {
      $.blockUI({ 
      "message": "処理中です。お待ちください。", 
      "css": {
      "padding": "10px 30px",
      "font-size": "20px",
      "font-weight": "bold"
      } 
      });
      });


      {% block script_onload %}{% endblock %}
      }
    </script>


    <div id="dialog" style="display:none;"><p></p></div>
    {% block html_body %} {% endblock %}
  </body>

</html>