myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

settings_amazon/urls.py
from django.urls import path
from rest_framework import routers
from . import views
#from .views import UserViewSet, EntryViewSet

from django.conf.urls import url, include

app_name = 'settings_amazon'

urlpatterns = [
    path('api_settings/', views.api_settings, name='api_settings'),
    path('default/', views.default_settings, name='default'),
    path('exclude_asin', views.exclude_asin, name='exclude_asin'),
    path('delete_exclude_asin', views.delete_exclude_asin, name='delete_exclude_asin'),
    path('brand/', views.brand_settings, name='brand'),
    path('delete_brands/', views.delete_brands, name='delete_brands'),
    path('category/', views.category, name='category'),
    path('category_parent', views.category_parent, name='category_parent'),
    path('category_child', views.category_child, name='category_child'),
    path('feed_price_settings', views.feed_price_settings, name='feed_price_settings'),
    path('api/token_validation', views.token_validation, name='api_token_validation'),
]

router = routers.DefaultRouter()
router.register(r'amazon_category', views.AmazonParentCategorySerializerViewSet)
router.register(r'amazon_brand', views.AmazonBrandSerializerViewSet)
router.register(r'amazon_category_user', views.AmazonParentCategoryUserSerializerViewSet)
router.register(r'amazon_child_category', views.AmazonChildCategorySerializerViewSet)
router.register(r'amazon_child_category_user', views.AmazonChildCategoryUserSerializerViewSet)

top/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

settings_amazon/models.py
from django.db import models
from django.core.validators import MaxValueValidator

# AmazonAPI設定


class AmazonAPI(models.Model):
    class Meta:
        db_table = 'amazon_api'
        verbose_name = 'API設定(各ユーザ)'
        verbose_name_plural = 'API設定(各ユーザ)'

    access_key = None
    secret_key = None
    region = None
    marketplace_id = None

    account_id = models.CharField(verbose_name="出品者ID", max_length=128)
    auth_token = models.CharField(
        verbose_name="認証トークン", max_length=128, null=True)
    author = models.ForeignKey(
        'accounts.User', on_delete=models.CASCADE, db_index=True)
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)
    validated_date = models.DateTimeField(verbose_name="検証日時", null=True)

    def __str__(self):
        return self.account_id


# プルダウンの選択肢
CONDITION_CHOICES = (
    ('New', '新品'),
    ('Refurbished', '再生品'),
    ('UsedLikeNew', '中古-ほぼ新品'),
    ('UsedVeryGood', '中古-非常に良い'),
    ('UsedGood', '中古-良い'),
    ('UsedAcceptable', '中古-可'),
    ('CollectibleLikeNew', 'コレクター商品-ほぼ新品'),
    ('CollectibleVeryGood', 'コレクター商品-非常に良い'),
    ('CollectibleGood', 'コレクター商品-良い'),
    ('CollectibleAcceptable', 'コレクター商品-可'),
)

# Amazonデフォルト設定


class AmazonDefaultSettings(models.Model):
    class Meta:
        db_table = 'amazon_default_settings'

    condition_type = models.CharField(
        verbose_name="コンディション", max_length=32, choices=CONDITION_CHOICES, null=True, blank=True)
    condition_note = models.TextField(
        verbose_name="コンディション説明", null=True, blank=True)
    part_number = models.CharField(
        verbose_name="メーカー型番", max_length=128, null=True, blank=True)
    fulfillment_latency = models.IntegerField(
        verbose_name="リードタイム（日）", null=True, blank=True)
    standard_price_points = models.IntegerField(
        verbose_name="ポイント(デフォルト値)", null=True, blank=True, default=0, validators=[MaxValueValidator(50)])
    new_item_points = models.IntegerField(
        verbose_name="ポイント(新規出品)", null=True, blank=True)
    new_auto_item_points = models.IntegerField(
        verbose_name="ポイント(新規出品自動化)", null=True, blank=True)
    ride_item_points = models.IntegerField(
        verbose_name="ポイント(相乗り出品)", null=True, blank=True)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.condition_type

# Amazonブランド設定


class AmazonBrand(models.Model):
    class Meta:
        db_table = 'amazon_brand'

    local_id = None
    brand_name = models.CharField(verbose_name="ブランド名", max_length=256)
    author = models.ForeignKey(
        'accounts.User', on_delete=models.CASCADE, db_index=True)
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.brand_name

# 禁止ASIN


class ExcludeAsin(models.Model):
    class Meta:
        db_table = 'amazon_exclude_asin'
        verbose_name = '禁止ASIN個別設定'
        verbose_name_plural = '禁止ASIN個別設定'

    local_id = None
    asin = models.CharField(verbose_name="禁止ASIN", max_length=16)
    memo = models.CharField(
        verbose_name="メモ", max_length=256, null=True, blank=True)
    author = models.ForeignKey(
        'accounts.User', on_delete=models.CASCADE, db_index=True)
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return '[{}] {}'.format(self.author.username, self.asin)


class ExcludeAsinMaster(models.Model):
    class Meta:
        db_table = 'amazon_exclude_asin_master'
        verbose_name = '新規ユーザー禁止ASINマスタ'
        verbose_name_plural = '新規ユーザー禁止ASINマスタ'

    local_id = None
    asin = models.CharField(verbose_name="禁止ASIN", max_length=16)

    def __str__(self):
        return self.asin


# Amazon出品プライス設定
class AmazonFeedPriceSettings(models.Model):
    class Meta:
        db_table = 'amazon_feed_price_settings'

    margin_new = models.FloatField(verbose_name="新規出品時の利益設定倍率（仕入れ元価格に対する倍率）")
    margin_offer = models.FloatField(
        verbose_name="相乗り出品時の利益設定倍率（仕入れ元価格に対する倍率）")
    margin_new_url = models.IntegerField(verbose_name="金額（円）", null=True)

    margin_offer_url = models.IntegerField(verbose_name="最低利益額（円）", null=True)
    margin_offer_percent_url = models.FloatField(
        verbose_name="最低利益率（％）　※0: チェックしない", null=True, default=0)
    offset_offer_price_url = models.IntegerField(
        verbose_name="相乗り販売価格（円）", null=True)
    lowest_offer_price_url = models.IntegerField(
        verbose_name="最低販売価格（円）", null=True)
    default_minimum_item_price = models.IntegerField(
        verbose_name='新規出品時の最低販売価格(円)', null=True, default=3000)

    author = models.ForeignKey(
        'accounts.User', on_delete=models.CASCADE, db_index=True)
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.author.username


# Amazon大カテゴリー(システム用)
class AmazonParentCategory(models.Model):
    class Meta:
        db_table = 'amazon_parent_category'
        verbose_name = '大カテゴリー設定'
        verbose_name_plural = '大カテゴリー設定'

    display_order = models.IntegerField(verbose_name="表示順序", db_index=True)
    name = models.CharField(verbose_name="名称", max_length=256)
    value = models.CharField(verbose_name="値", max_length=256)
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.name

# Amazon大カテゴリー(ユーザ用)


class AmazonParentCategoryUser(models.Model):
    class Meta:
        db_table = 'amazon_parent_category_user'

    display_order = models.IntegerField(verbose_name="表示順序", db_index=True)
    name = models.CharField(verbose_name="名称", max_length=256)
    value = models.CharField(verbose_name="値", max_length=256, db_index=True)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.name


# CSV
class CSVFormat(models.Model):
    ''' 新規出品フォーマットの Index を指し示す '''
    class Meta:
        db_table = 'amazon_csv_format'
        verbose_name = '新規出品用CSVフォーマット'
        verbose_name_plural = '新規出品用CSVフォーマット'

    format = models.CharField(verbose_name="フォーマット",
                              max_length=64, db_index=True)
    fields = models.IntegerField(verbose_name="フィールド数")
    feed_product_type = models.IntegerField(verbose_name="商品タイプ")
    item_sku = models.IntegerField(verbose_name="出品者SKU")
    brand_name = models.IntegerField(verbose_name="ブランド名")
    item_name = models.IntegerField(verbose_name="商品名")
    external_product_id = models.IntegerField(verbose_name="商品コード(JANコード等)")
    external_product_id_type = models.IntegerField(verbose_name="商品コードのタイプ")
    manufacturer = models.IntegerField(verbose_name="メーカー名")
    recommended_browse_nodes = models.IntegerField(verbose_name="推奨ブラウズノード")
    quantity = models.IntegerField(verbose_name="在庫数")
    standard_price = models.IntegerField(verbose_name="商品の販売価格")
    main_image_url = models.IntegerField(verbose_name="商品メイン画像URL")
    part_number = models.IntegerField(verbose_name="メーカー型番")
    condition_type = models.IntegerField(verbose_name="商品のコンディション")
    condition_note = models.IntegerField(verbose_name="商品のコンディション説明")
    product_description = models.IntegerField(verbose_name="商品説明文")
    bullet_point = models.IntegerField(verbose_name="商品の仕様")
    generic_keywords = models.IntegerField(verbose_name="検索キーワード")
    other_image_url1 = models.IntegerField(verbose_name="商品サブ画像URL1")
    other_image_url2 = models.IntegerField(verbose_name="商品サブ画像URL2")
    other_image_url3 = models.IntegerField(verbose_name="商品サブ画像URL3")
    fulfillment_latency = models.IntegerField(
        verbose_name="リードタイム(出荷までにかかる作業日数)")
    standard_price_points = models.IntegerField(verbose_name="ポイント", validators=[MaxValueValidator(50)])
    is_adult_product = models.IntegerField(default=85, verbose_name="アダルト商品")
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.format

# Amazonシステムカテゴリー（ホビー）
class AmazonHobbiesCategory(models.Model):
    class Meta:
        db_table = 'amazon_hobbies_category'
        verbose_name = '詳細カテゴリー設定(ホビー)'
        verbose_name_plural = '詳細カテゴリー設定(ホビー)'

    display_order = models.IntegerField(verbose_name="表示順序", db_index=True)
    name = models.CharField(verbose_name="名称", max_length=256)
    format = models.CharField(verbose_name="フォーマット", max_length=64)
    feed_product_type = models.CharField(verbose_name="商品タイプ", max_length=64)
    value = models.CharField(verbose_name="推奨ブラウズノード",
                             max_length=64, db_index=True)
    created_date = models.DateTimeField(verbose_name="作成日", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="更新日", auto_now=True)

    def __str__(self):
        return self.name


# Amazonユーザカテゴリー（ホビー）
class AmazonHobbiesCategoryUser(models.Model):
    class Meta:
        db_table = 'amazon_hobbies_category_user'

    display_order = models.IntegerField(verbose_name="表示順序", db_index=True)
    name = models.CharField(verbose_name="名称", max_length=256)
    format = models.CharField(verbose_name="フォーマット", max_length=64)
    feed_product_type = models.CharField(verbose_name="商品タイプ", max_length=64)

settings_amazon/forms.py
from django import forms
from .models import AmazonAPI, AmazonDefaultSettings, AmazonBrand, AmazonFeedPriceSettings, ExcludeAsin

# API設定


class AmazonAPIForm(forms.ModelForm):
    class Meta:
        model = AmazonAPI
        fields = ['account_id', 'auth_token']

# デフォルト設定


class AmazonDefaultSettingsForm(forms.ModelForm):
    class Meta:
        model = AmazonDefaultSettings
        fields = [
            'condition_type', 'condition_note', 'part_number',
            'fulfillment_latency', 'standard_price_points',
            'new_item_points', 'new_auto_item_points', 'ride_item_points',
        ]

    def __init__(self, *args, **kwargs):
        super(AmazonDefaultSettingsForm, self).__init__(*args, **kwargs)
        self.fields['condition_type'].required = False
        self.fields['condition_note'].required = False
        self.fields['part_number'].required = False
        self.fields['fulfillment_latency'].required = False
        self.fields['standard_price_points'].required = False
        self.fields['new_item_points'].required = False
        self.fields['new_auto_item_points'].required = False
        self.fields['ride_item_points'].required = False


# ブランド設定
class AmazonBrandForm(forms.ModelForm):
    class Meta:
        model = AmazonBrand
        fields = ['brand_name']


# 禁止ASIN
class ExcludeAsinForm(forms.ModelForm):
    class Meta:
        model = ExcludeAsin
        fields = ['asin', 'memo']


# 上乗せ金額設定
class AmazonFeedPriceSettingsForm(forms.ModelForm):
    class Meta:
        model = AmazonFeedPriceSettings
        fields = ['margin_new', 'margin_offer', 'default_minimum_item_price', 'margin_offer_url',
                  'margin_offer_percent_url', 'offset_offer_price_url', 'lowest_offer_price_url']

settings_amazon/templates/settings_amazon/api.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %} AmazonAPI設定{% endblock %}

{% block script_onload %}

Utils.selectAmazonSetting();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

{% endblock %}

{% block html_body %} 
<div class="container">
  <center>
    <h2>AmazonAPI設定</h2>
    <br>
    <p>MWS認証トークンを設定してください。</p>
    <p><span style="font-weight: bold;">入力内容が間違えていると機能の大半が利用できないため、確認ボタンによるチェックを強く勧めます。</span></p>
  </center>

  <form class="form-horizontal" action="{% url 'settings_amazon:api_settings'  %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.account_id.label_tag }}<br>
      {{ form.account_id | add_class:"form-control" }}<br>
    </div>
    <div class="form-group">
      {{ form.auth_token.label_tag }}<br>
      {{ form.auth_token | add_class:"form-control" }}<br>
    </div>
    <div id="check-result" style="display: none;">
      <p>チェック結果: <span id="check-result-text" style="font-weight: bold; color: red;"></span></p>
    </div>
    <button id="validation" type="button">入力内容の確認</button>&nbsp;
    <input type="submit" value="登録" />
  </form>
</div>
  
<script type="text/javascript">
  $(function() {
    $('#validation').click(function() {
      $('#check-result-text').text('現在入力内容をチェック中です...');
      $('#check-result').show();
      var csrfToken = $($('input[name="csrfmiddlewaretoken"]')[0]).val();
      $.post({
        url: "{% url 'settings_amazon:api_token_validation' %}",
        data: {
          csrfmiddlewaretoken: csrfToken,
          account_id: $('#id_account_id').val(),
          auth_token: $('#id_auth_token').val(),
          keyword: 'フィギュア'
        }
      }).done(function(data) {
        $('#check-result-text').text(data.message);
      }).fail(function() {
        $('#check-result-text').text('入力内容の確認に失敗しました。');
      });
    });
  });
</script>
{% endblock %}

settings_amazon/templates/settings_amazon/brand.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %} Amazonブランド設定{% endblock %}


{% block script_onload %}

Utils.selectAmazonSetting();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

{% endblock %}

{% block html_body %} 
<div class="container">
  <center><h2>Amazonブランド設定</h2></center>

  <form class="form-horizontal" action="{% url 'settings_amazon:brand'  %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.brand_name.label_tag }}<br>
      {{ form.brand_name | add_class:"form-control" }}<br>
    </div>
    <input type="submit" value="登録" />
  </form>

  <br>

  {% if brands.count > 0 %} 
  <form class="form-horizontal" action="{% url 'settings_amazon:delete_brands'  %}" method="post">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="col-xs-1">ID</th>
          <th class="col-xs-1">削除</th>
          <th>ブランド名</th>
        </tr>
      </thead>
      <tbody>
        {% for brand in brands %}
        <tr>
	  <td>{{ brand.id }}</td>
          <td><input type="checkbox" name="delete_ids" value="{{ brand.id }}"></td>
          <td>{{ brand.brand_name }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% csrf_token %}
    <input type="submit" value="削除">
  </form>
</div>
</form>
</div>
{% endif %}
{% endblock %}

settings_amazon/templates/settings_amazon/category.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %} Amazonカテゴリー順序設定{% endblock %}

{% block script_onload %}

Utils.selectAmazonSetting();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

{% endblock %}

{% block html_body %} 
<div class="container">
  <center><h2>Amazonカテゴリー順序設定</h2></center>

  <button type="button"onclick="location.href='{% url 'settings_amazon:category_parent'  %}'">大カテゴリー設定</button>
  <button type="button"onclick="location.href='{% url 'settings_amazon:category_child'   %}'">詳細カテゴリー設定</button>
</div>
<!-- JavaScripts -->

<script type="text/javascript" src="{% static 'js/ListBoxMove.js' %}"></script>
<script type="text/javascript" src="{% static 'js/AmazonCategory.js' %}"></script>

{% endblock %}

settings_amazon/templates/settings_amazon/category_child.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %} Amazonカテゴリー順序設定{% endblock %}

{% block script_onload %}

Utils.selectAmazonSetting();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

AmazonCategory.setSelectedParentCategory();

{% endblock %}

{% block html_body %} 
<div class="container">
  <center><h2>Amazonカテゴリー順序設定</h2></center>


  <button type="button"onclick="location.href='{% url 'settings_amazon:category_parent'  %}'">大カテゴリー設定</button>
  <button type="button"onclick="location.href='{% url 'settings_amazon:category_child'   %}'">詳細カテゴリー設定</button>
  <br>
  <br>

  <div class="form-group">
    <select id="selected_parent_category" onChange="AmazonCategory.onChangeSelectedParentCategory();"></select>
    <table>
      <tr>
	<td>
	  <select id="selectable" multiple="multiple" class="form-control" size="15" style="width: 300px">
	  </select>
	</td>
	<td style="padding-left:10px;padding-right:5px;">
	  <button type="button" id="left-btn">&gt;&gt;</button>
	  <br>
	  <br>
	  <button type="button" id="right-btn">&lt;&lt;</button>
	</td>
	<form class="form-horizontal" action="{% url 'settings_amazon:category_child' %}" method="post">
	  <td>
	    <select id="selected" name="selected" multiple="multiple" class="form-control selectpicker" size="15" style="width: 300px"> </select>
	  </td>
      </tr>
    </table>
    <br>
    <input type="hidden" id="category" name="category" value="">
    {% csrf_token %}
    <input type="submit" id="submit"  value="登録" onclick="AmazonCategory.selectAllSelectedCategory();">
    </form>
  </div>
</div>
<!-- JavaScripts -->

<script type="text/javascript" src="{% static 'js/ListBoxMove.js' %}"></script>
<script type="text/javascript" src="{% static 'js/AmazonCategory.js' %}"></script>

{% endblock %}

settings_amazon/templates/settings_amazon/category_parent.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %} Amazonカテゴリー順序設定{% endblock %}

{% block script_onload %}

Utils.selectAmazonSetting();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

<!--選択可能な大カテゴリー -->
AmazonCategory.setSelectableCategory();
<!--選択済大カテゴリー -->
AmazonCategory.setSelectedCategory();

{% endblock %}

{% block html_body %} 
<div class="container">
  <center><h2>Amazonカテゴリー順序設定</h2></center>


  <button type="button"onclick="location.href='{% url 'settings_amazon:category_parent'  %}'">大カテゴリー設定</button>
  <button type="button"onclick="location.href='{% url 'settings_amazon:category_child'   %}'">詳細カテゴリー設定</button>
  <br>
  <br>

  <div class="form-group">

    <table>
      <tr>
	<td>
	  <select id="selectable" multiple="multiple" class="form-control" size="15" style="width: 300px">
	  </select>
	</td>
	<td style="padding-left:10px;padding-right:5px;">
	  <button type="button" id="left-btn">&gt;&gt;</button>
	  <br>
	  <br>
	  <button type="button" id="right-btn">&lt;&lt;</button>
	</td>
	<form class="form-horizontal" action="{% url 'settings_amazon:category_parent' %}" method="post">
	  <td>
	    <select id="selected" name="selected" multiple="multiple" class="form-control selectpicker" size="15" style="width: 300px"> </select>
	  </td>
      </tr>
    </table>
    <br>
    {% csrf_token %}
    <input type="submit" value="登録" onclick="AmazonCategory.selectAllSelectedCategory();">
    
    </form>
  </div>
</div>
<!-- JavaScripts -->

<script type="text/javascript" src="{% static 'js/ListBoxMove.js' %}"></script>
<script type="text/javascript" src="{% static 'js/AmazonCategory.js' %}"></script>

{% endblock %}

settings_amazon/templates/settings_amazon/default.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %} Amazonデフォルト設定{% endblock %}

{% block script_onload %}

Utils.selectAmazonSetting();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

{% endblock %}

{% block html_body %} 
<div class="container">
  <center><h2>Amazonデフォルト設定</h2></center>

  <form class="form-horizontal" action="{% url 'settings_amazon:default'  %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.condition_type.label_tag }}<br>
      {{ form.condition_type | add_class:"form-control" }}<br>
    </div>
    <div class="form-group">
      {{ form.condition_note.label_tag }}<br>
      {{ form.condition_note | add_class:"form-control" }}<br>
    </div>
    <div class="form-group">
      {{ form.part_number.label_tag }}<br>
      {{ form.part_number | add_class:"form-control" }}<br>
    </div>
    <div class="form-group">
      {{ form.fulfillment_latency.label_tag }}<br>
      {{ form.fulfillment_latency | add_class:"form-control" }}<br>
    </div>
    <div class="form-group">
      {{ form.standard_price_points.label_tag }}<br>
      {{ form.standard_price_points | add_class:"form-control" }}<br>
    </div>
    <div class="form-group">
      {{ form.new_item_points.label_tag }}<small>&nbsp;※入力がない場合、ポイント(デフォルト値)が利用されます。</small><br>
      {{ form.new_item_points | add_class:"form-control" }}<br>
    </div>
    <div class="form-group">
      {{ form.ride_item_points.label_tag }}<small>&nbsp;※入力がない場合、ポイント(デフォルト値)が利用されます。</small><br>
      {{ form.ride_item_points | add_class:"form-control" }}<br>
    </div>
    <div class="form-group">
      {{ form.new_auto_item_points.label_tag }}<small>&nbsp;※入力がない場合、ポイント(デフォルト値)が利用されます。</small><br>
      {{ form.new_auto_item_points | add_class:"form-control" }}<br>
    </div>
    <input type="submit" value="登録" />
  </form>
</div>

{% endblock %}

settings_amazon/templates/settings_amazon/exclude_asin.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}メルカリッチくん{% endblock %}


{% block script_onload %}

Utils.selectAmazonSetting();
{% if message %}
Utils.dialog('{{ message }}', '{{ message_detail}}');
{% endif %}

{% endblock %}

{% block html_body %} 
<div class="container">
  <center><h2>禁止ASIN設定</h2></center>
  <br>
  <b>出品を禁止したいASINを設定します。</b>
  <br>
  <br>
  <form class="form-horizontal" action="{% url 'settings_amazon:exclude_asin'  %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      {{ form.asin.label_tag }}<br>
      {{ form.asin | add_class:"form-control" }}<br>
      {{ form.memo.label_tag }}<br>
      {{ form.memo | add_class:"form-control" }}<br>
    </div>
    <input type="submit" value="登録" />
  </form>

  <br>

  {% if asins.count > 0 %} 
  <form class="form-horizontal" action="{% url 'settings_amazon:delete_exclude_asin'  %}" method="post">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="col-xs-1">ID</th>
          <th class="col-xs-1">削除</th>
          <th>ASIN</th>
	  <th>メモ</th>
        </tr>
      </thead>
      <tbody>
        {% for asin in asins %}
        <tr>
          <td>{{ asin.local_id }}</td>
          <td><input type="checkbox" name="delete_ids" value="{{ asin.id }}"></td>
          <td>{{ asin.asin }}</td>
	  <td>{% if asin.memo != None %}{{ asin.memo }}{% endif %}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% csrf_token %}
    <input type="submit" value="削除">
  </form>
</div>
{% endif %}

{% endblock %}